### ISSUE TITLE
 cls_branch_max  problem

### ISSUE THREAD

**Issue by RockMan1966** [Owais-Ansari/Unet3plus#1]
Thanks for the author's work, hello author, may I ask if the last classification module, cls_branch_max, is not the output of the model.

**Comment by Owais-Ansari** [comment]
Hi, Thank you for posting your comment. Indeed the output of the Unet3PlusGLCM is cls_branch_max.

you can visit the “utils/models.py” file


Let me know if your have any further question. I would be happy to answer.
